title: Yusuf YILDIZ
author:
  name: yusufyildiz34
  email: mail@@yusufyildiz.co
description: >
  I've been working as Fullstack Java Developer over 15 years.
favicon: "/favicon.ico"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
google_analytics: G-1J0P085LKC
