title: Yusuf YILDIZ
author:
  name: yusufyildiz34
  email: mail@@yusufyildiz.co
description: >
  I've been working as Fullstack Java Developer over 15 years and building Highly Available, Scalable and Fault-tolerant Distributed Systems.
favicon: "/favicon.ico"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
remote_theme: jekyll/minima
google_analytics: G-1J0P085LKC
